version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:0.8.1-pg16-bookworm
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cv-evaluator
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '6380:6379'
    volumes:
      - redis:/data

volumes:
  postgres:
  redis:
